/**
 * Privacy/data-lifecycle error codes (PR-PRIVACY). Additive — follows the
 * same `ApiError(status, message, details, code)` convention used by
 * constants/billing.ts's BillingErrorCode; never a rewrite of ApiError
 * itself.
 */
export enum PrivacyErrorCode {
  PRIVACY_EXPORT_ALREADY_PENDING = 'PRIVACY_EXPORT_ALREADY_PENDING',
  PRIVACY_EXPORT_NOT_FOUND = 'PRIVACY_EXPORT_NOT_FOUND',
  PRIVACY_EXPORT_EXPIRED = 'PRIVACY_EXPORT_EXPIRED',
  PRIVACY_DELETE_CONFIRMATION_REQUIRED = 'PRIVACY_DELETE_CONFIRMATION_REQUIRED',
  PRIVACY_REAUTH_REQUIRED = 'PRIVACY_REAUTH_REQUIRED',
  PRIVACY_DELETION_IN_PROGRESS = 'PRIVACY_DELETION_IN_PROGRESS',
  PRIVACY_DELETION_PARTIAL = 'PRIVACY_DELETION_PARTIAL',
  CANDIDATE_PRIVACY_ACCESS_DENIED = 'CANDIDATE_PRIVACY_ACCESS_DENIED',
  LEGAL_HOLD_ACTIVE = 'LEGAL_HOLD_ACTIVE',
  CONSENT_REQUIRED = 'CONSENT_REQUIRED',
  POLICY_REACCEPTANCE_REQUIRED = 'POLICY_REACCEPTANCE_REQUIRED',
}
